# === Process Data --------------------------------------------------------
# Alec Robitaille ---------------------------------------------------------



# Packages ----------------------------------------------------------------
library(spatsoc)
library(data.table)
library(asnipe)


# Input -------------------------------------------------------------------
DT <- readRDS('output/2-sub-data.Rds')
alloc.col(DT)


# Process -----------------------------------------------------------------
# Group relocations to daily trajectories, using a threshold of 1 day
group_times(
	DT,
	datetime = 'datetime',
	threshold = '1 day'
)

# EPSG code for example data
utm <- '+init=epsg:32736'

# Group daily trajectories in space, using a threshold of 50 meters
group_lines(
	DT,
	threshold = 50,
	projection = utm,
	id = 'ID',
	coords = c('X', 'Y'),
	timegroup = 'timegroup',
	sortBy = 'datetime'
)

# Generate group by individual matrix
#   group column generated by spatsoc::group_pts
gbi <- get_gbi(DT = DT, group = 'group', id = 'ID')


# Generate network
net <- get_network(gbi,
									 data_format = "GBI",
									 association_index = "SRI")

# Output ------------------------------------------------------------------
saveRDS(DT, 'output/4-group-lines.Rds')
saveRDS(net, 'output/4-network-lines.Rds')
