#' Network Points
#'
#' @author Alec Robitaille
#'
#' @return
#' @export
#'
#' @examples
network_pts <- function(DT, tempthresh, spatthresh,
												datetime = 'datetime', coords = c('X', 'Y')) {

	data.table::alloc.col(DT)

	# Group relocations in time, using a threshold of 5 minutes
	spatsoc::group_times(
		DT,
		datetime = datetime,
		threshold = tempthresh
	)

	# Group relocations in space, using a threshold of 50 meters
	spatsoc::group_pts(
		DT,
		threshold = spatthresh,
		id = 'ID',
		coords = c('X', 'Y'),
		timegroup = 'timegroup'
	)

	# Generate group by individual matrix
	#   group column generated by spatsoc::group_pts
	gbi <- spatsoc::get_gbi(DT = DT, group = 'group', id = 'ID')


	# Generate network
	net <- asnipe::get_network(gbi,
										 data_format = "GBI",
										 association_index = "SRI")

}
