---
title: Troubleshooting
subtitle: and problem solving in R
author: Alec L. Robitaille
institute:  Wildlife Evolutionary Ecology Lab <br> Memorial University
date: "2022-04-18"
output: 
  xaringan::moon_reader:
    nature:
      beforeInit: "2022-04-18-troubleshooting.js"
      highlightStyle: agate
      slideNumberFormat: |
        <div class="progress-bar-container">
          <div class="progress-bar" style="width: calc(%current% / %total% * 100%);">
          </div>
        </div>
    css: ["2022-04-18-troubleshooting-xaringan-themer.css"]
---

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
base_color <- "#b68e7d"
lighter_base <- lighten_color(base_color, 0.35)
h4_color <- darken_color(lighter_base, 0.2)

regular <- "1rem"
small <- "0.75rem"
h1 <- "2.25rem"
h2 <- "2rem"
h3 <- "1.3rem"

code_color <- darken_color(base_color, 0.7)

style_mono_dark(
	outfile = '2022-04-18-troubleshooting-xaringan-themer.css',
  base_color = base_color,
  link_color = lighter_base,
  code_inline_color = lighter_base,
	left_column_selected_color = apply_alpha(base_color, 0.7),
  code_inline_background_color = code_color,

  text_font_size = "1.5rem",
  header_h3_font_size = "0.75rem",
  extra_css = list(
		".remark-slide-content h4" = list("font-size" = regular, "color" = h4_color),
		".left-column" = list("width" = "20%", 'font-size' = regular,
													"height" = '95%'
													# 'border-right' = '0.1px solid var(--link-color)'
													),
		".hljs-agate .hljs" = list("background" = code_color, "color" = lighter_base),
		".panelset" = list("font-size" = regular),
		".medium" = list("font-size" = regular),
		".small" = list("font-size" = small),
		".footnote" = list("font-size" = small,  "left" = '75%'),
		".title-slide h1" = list("font-size" = h1),
		".title-slide h2" = list("font-size" = h2),
		".title-slide h3" = list("font-size" = h3),
		"img" = list("box-shadow" = "2px 2px 5px var(--link-color)")
	),
  header_font_google = google_font("Roboto Slab", "200"),
  text_font_google = google_font("Roboto Slab", "300"),
  code_font_google   = google_font("Fira Mono")
)
xaringanExtra::use_panelset()
```



.left-column[
<br><br><br><br><br><br>
### **Discussion**
### Prevention
### Simplifying
### and other strategies
### Resources
]


---

.left-column[
<br><br><br><br><br><br>
### **Discussion**
### Prevention
### Simplifying
### and other strategies
### Resources
]


#### What are your strategies for...


Troubleshooting errors?

Problem solving?

Learning a new package?

Starting a new analysis?



---

.left-column[
<br><br><br><br><br><br>
### Discussion
### **Prevention**
### Simplifying
### and other strategies
### Resources
]

#### First, some preventative measures

Adjust RStudio settings [[1]](https://csgillespie.github.io/efficientR/set-up.html#rstudio-options)

Use an RStudio project, relative file paths

Keep R, R packages, and OS updated


---

.left-column[
<br><br><br><br><br><br>
### Discussion
### **Prevention**
### Simplifying
### and other strategies
### Resources
]

#### Extras

Track package versions with `renv`

Reproducible workflows with `targets`

Use Git

???
renv tracks package versions for each project, so global updates to packages 
won't break eg. older projects

Git helps with the feedback cycle of coding -> tracked changes -> commit -> coding
Also, Git lets you create branches to explore alternatives, without 
breaking your current working versions

A workflow defined in targets ensures steps are only rerun when they are outdated 
and helps branching by eg. individuals or study sites


---


.left-column[
<br><br><br><br><br><br>
### Discussion
### Prevention
### **Simplifying**
### and other strategies
### Resources
]

#### Generate minimal data

Simplest: built in or package data  
`data(mtcars)`  
`palmerpenguins`  

Or build your own:  
Identify columns, types, units, limits
and generate fake data


.footnote[
FIX LINK
[`R/simplify-data.R`](k)
]

<!--
~~MWE~~ MBE ? minimum broken example? you have a maximum broken example.. 

Reprex

https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html
https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example/16532098
https://reprex.tidyverse.org/articles/datapasta-reprex.html


Built in data
https://stat.ethz.ch/R-manual/R-patched/library/datasets/html/00Index.html
example data from the package you are having trouble with


Types of errors
rlang
-->

---
.left-column[
<br><br><br><br><br><br>
### Discussion
### Prevention
### **Simplifying**
### and other strategies
### Resources
]

#### Learning a new package

1. Generate minimal data
1. 


---
.left-column[
<br><br><br><br><br><br>
### Discussion
### Prevention
### **Simplifying**
### and other strategies
### Resources
]

#### Troubleshooting





---

.left-column[
<br><br><br><br><br><br>
### Discussion
### Prevention
### Simplifying
### **and other strategies**
### Resources
]

Explore the traceback [[1]](https://adv-r.hadley.nz/debugging.html#traceback)

Read (and reread) documentation

Restart R, clear the environment

Update R, R packages, OS

Check your .Rprofile, .Renviron
[[2]](https://csgillespie.github.io/efficientR/set-up.html#an-overview-of-rs-startup-files=), [[3]](https://usethis.r-lib.org/reference/edit.html)

GitHub Issues [(e.g. [4])](https://github.com/rstudio/bookdown/issues/1263)  
Stack Overflow [(e.g. [5])](https://stackoverflow.com/questions/42149427/group-membership-by-pairwise-criteria-matching)

Ask for help! 



---

.left-column[
<br><br><br><br><br><br>
### Discussion
### Prevention
### Simplifying
### and other strategies
### **Resources**
]

-[`reprex`: introduction](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html)  
-[SO: Making a great R reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example/16532098)  
-[`reprex`: datapasta](https://reprex.tidyverse.org/articles/datapasta-reprex.html)


-[Advanced R: Debugging](https://adv-r.hadley.nz/debugging.html0)


-[Description of startup files](https://csgillespie.github.io/efficientR/set-up.html#an-overview-of-rs-startup-files=)  
-[Editing startup files](https://usethis.r-lib.org/reference/edit.html)

-[`targets` manual](https://books.ropensci.org/targets/)  
-[`renv` documentation](https://rstudio.github.io/renv/)

-[Efficient R: Version control](https://csgillespie.github.io/efficientR/collaboration.html#version-control)  
-[Happy Git with R](https://happygitwithr.com/)
