---
title: "Reading and writing spatial data in R"
output:
  learnr::tutorial:
    allow_skip: false
runtime: shiny_prerendered
description: >
  This tutorial demonstrates reading and writing spatial data in R, and has a basic comparison of different spatial file formats. 
---

```{r setup, include=FALSE}
library(learnr)
knitr::opts_chunk$set(echo = TRUE, 
                      highlight = TRUE)

tutorial_options(exercise.eval = FALSE)
```


<!--

  allow_retry = TRUE
  random_answer_order

echo = FALSE

quiz (
questions..
)
post_message

-->

## Packages

```{r packages}
library(sf)
library(mapview)
library(data.table)
```

## Example data

```{r data}
# Load breweries data from mapview
data(breweries)

# Have a look!
plot(breweries, max.plot = 1)
```

```{r map}
# Or interactive:
mapview(breweries)

```


## Spatial file formats

```{r, echo = FALSE}
knitr::kable(fread('../../extdata/data-formats.csv', header = TRUE, col.names = c('File format', '')))
```

Note: We are ignoring raster-based file formats for now. 


### Are these available in R?

```{r drivers, exercise = TRUE, exercise.eval = FALSE}
# In the sf package, the function st_drivers() gives us all available file formats
drivers <- st_drivers()

# Explore the drivers to find a couple of the above file formats
# If we convert to a data.table we can filter easily
data.table(drivers)[name == 'GPKG']
```


## Writing spatial data

Since we have the `breweries` data loaded, let's write it out using `sf`. 

```{r write, exercise = TRUE, exercise.eval = TRUE}
dir.create('input')


```
