---
output: github_document
---

# Personal R Packages
A workshop delivered by Alec Robitaille to the Wildlife Evolutionary Ecology Lab at Memorial University on 2018-10-25.

```{bash}
tree
```

## Details

The presentation is found in the `core` repo at `core/Workshops/Personal-R-Packages/ presentation/Personal-R-Packages.html`

Pull the `core` repo to check out the source. This presentation was written in `RMarkdown` using the `xaringan` package by Yihui Xie.

The code chunks are pulled out of the presentation and stored in `R/Chunks-PersonalPackages.R`.

The setup script (`R/Setup-PersonalPackages.R`) is combined with the code chunks to produce a worksheet (`R/Worksheet-PersonalPackages.R`).

Follow along with this worksheet...

### Directions

1. Open the Personal-R-Packages project (`Personal-R-Packages.Rproj`) as we go through the presentation. 
1. Open the worksheet. 
1. Load libraries, generate fake data, etc. Data for this presentation is stored in an `input` folder. 

    Section label `### From Chunks-From-PersonalPackages.R ----` indicates the beginning of the chunks from the presentation. 

1. Run through the examples of excess typing from copy+paste. 
1. Make the `calc` function instead. 
1. Use it 3 ways. 
1. Learn about formals, body and environment. Try this with another function you use often!
1. Three examples of using subsets of your data. 
1. More examples of functions. 
1. Comparison of using the `seq_along` or a unique combination `data.table`. 
