#' Network Lines
#'
#' @author Alec Robitaille
#'
#' @return
#' @export
#'
#' @examples
network_lines <- function(DT, tempthresh, spatthresh,
												datetime = 'datetime', coords = c('X', 'Y'), ID = 'ID',
												projection) {

	data.table::alloc.col(DT)

	# Group relocations to daily trajectories, using a threshold of 1 day
	spatsoc::group_times(
		DT,
		datetime = datetime,
		threshold = tempthresh
	)

	# Group daily trajectories in space, using a threshold of 50 meters
	spatsoc::group_lines(
		DT,
		threshold = spatthresh,
		projection = projection,
		id = ID,
		coords = coords,
		timegroup = 'timegroup',
		sortBy = datetime
	)

	# Generate group by individual matrix
	#   group column generated by spatsoc::group_pts
	gbi <- spatsoc::get_gbi(DT = DT, group = 'group', id = 'ID')


	# Generate network
	net <- asnipe::get_network(gbi,
										 data_format = "GBI",
										 association_index = "SRI")

}
