# === Process Data --------------------------------------------------------
# Alec Robitaille ---------------------------------------------------------



# Packages ----------------------------------------------------------------
library(spatsoc)
library(data.table)
library(asnipe)


# Input -------------------------------------------------------------------
DT <- readRDS('output/2-sub-data.Rds')
alloc.col(DT)


# Process -----------------------------------------------------------------
# Group relocations in time, using a threshold of 5 minutes
group_times(
	DT,
	datetime = 'datetime',
	threshold = '5 minutes'
)

# Group relocations in space, using a threshold of 50 meters
group_pts(
	DT,
	threshold = 50,
	id = 'ID',
	coords = c('X', 'Y'),
	timegroup = 'timegroup'
)

# Generate group by individual matrix
#   group column generated by spatsoc::group_pts
gbi <- get_gbi(DT = DT, group = 'group', id = 'ID')


# Generate network
net <- get_network(gbi,
									 data_format = "GBI",
									 association_index = "SRI")

# Output ------------------------------------------------------------------
saveRDS(DT, 'output/3-group-locs.Rds')
saveRDS(net, 'output/3-network.Rds')
